name: ReactApplication Build And Deploy

on:
  push:
    branches:
      - "master"

jobs:
  buildAndDeployTos3:
                  runs-on: ubuntu-latest

                  steps:
                    - name: buildingApplication
                    - uses: actions/checkout@v1
                    - run:  npm run buid
                    - uses: jakejarvis/s3-sync-action@master
                      with:
                       args: --acl public-read --follow-symlinks --delete
                      env:
                        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
                        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                        AWS_REGION: 'us-east-1'
          
